services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-server-linux
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_PID=Developer
    ports:
      - "1435:1433"
    volumes:
      - mssql-data:/var/opt/mssql
      - ./backups:/backups
    networks:
      - mssql-network

volumes:
  mssql-data:

networks:
  mssql-network:
